#!/usr/bin/osascript

tell application "iTerm"
  set myWin to (create window with default profile)
	set the bounds of myWin to {50, 50, 636, 980}
  set myDir to POSIX path of ((path to me as text) & "::")

  tell current session of myWin
    set background color to {5000, 5000, 5000}
    set foreground color to {65535, 65535, 65535}
    set ANSI green color to {0, 65535, 0}
    set ANSI yellow color to {65535, 65535, 0}
    set ANSI red color to {65535, 0, 0}

    write text "cd " & myDir & " && ./xmas.sh"
    -- write text "./xmas.sh"
  end tell
end tell
